name: tests
on:
  # pull-request events are not triggered when a PR is merged
  # push events are not triggered when a PR created from a fork repository
  # So we need both to run tests on every PR and after merging
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      # For incremental builds
      CARGO_INCREMENTAL: 1
      CARGO_LLVM_COV_VERSION: 0.8.7
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        # For incremental builds
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: rustfmt, clippy

      # For incremental builds
      - name: git-restore-mtime
        uses: chetan/git-restore-mtime-action@d186aca54f8760da4dec55313195e51ed3ebb0b3 # v2.3

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-llvm-cov-${{ env.CARGO_LLVM_COV_VERSION }}-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo fmt --all -- --check

      - run: cargo clippy --all-targets --all-features -- -D warnings

      - run: cargo check

      - name: coverage
        run: |
          cargo install cargo-llvm-cov --version "${CARGO_LLVM_COV_VERSION}" --locked
          cargo llvm-cov --lcov --output-path coverage.lcov
